basePath: /api
host: localhost:8888
info:
  contact: {}
  title: Gin  Swagger  API
  version: "2.0"
paths:
  /helloworld:
    get:
      consumes:
      - application/json
      description: do ping
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 测试一下
      tags:
      - 测试
swagger: "2.0"
